### ISSUE TITLE
Java Client - Create Person

### ISSUE THREAD

**Issue by rochapaulo** [willianmga/hello-microservices#6]
Criar client API (java) para efetuar requests ao endpoint de criação de pessoas

exemplo de uso:

personClient.savePerson(person)

- Encapsular chamadas em HystrixCommands: https://github.com/Netflix/Hystrix/wiki/How-To-Use
Exemplos:
https://github.com/materasystems/crud-microservices/tree/master/crudmicroservices-client/src/main/java/com/matera/crudmicroservices/api/command

- Escrever testes automatizados

**Comment by willianmga** [comment]
finished
