### ISSUE TITLE
Java Client - Query Person

### ISSUE THREAD

**Issue by rochapaulo** [willianmga/hello-microservices#7]
Criar client API (java) para efetuar requests ao endpoint de consulta de pessoas, sendo

searchByID(String id)
searchBy(PersonQuery query)

Utilizar o padrão: Query Objects

Exemplo de uso:

PersonQuery query = 
new PersonQuery.Builder()
   .withFirstName("paulo")
   .withLastName("almeida")
   .withZipcode("87020210")
   .build()

client.searchBy(query)

Encapsular chamadas em HystrixCommands: https://github.com/Netflix/Hystrix/wiki/How-To-Use
Exemplos:
https://github.com/materasystems/crud-microservices/tree/master/crudmicroservices-client/src/main/java/com/matera/crudmicroservices/api/command

Escrever testes automatizados

**Comment by willianmga** [comment]
starting the implementation

**Comment by willianmga** [comment]
finished
